# Generated by Django 3.1.4 on 2021-04-12 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_assignment_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='assignment',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
