# Generated by Django 3.1.4 on 2021-04-12 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0010_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assignments.assignment'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='assignments.studentassignment'),
        ),
    ]
