# Generated by Django 3.1.4 on 2021-04-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0012_auto_20210413_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='added',
            field=models.BooleanField(default=False),
        ),
    ]
