# Generated by Django 3.1.4 on 2021-04-14 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0014_studentassignment_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='duedate',
            field=models.DateField(default=datetime.datetime(2021, 4, 15, 1, 5, 20, 228434)),
        ),
        migrations.AddField(
            model_name='assignment',
            name='subject',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='solution',
            name='submission_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 15, 1, 5, 20, 228434)),
        ),
    ]
