# Generated by Django 3.1.4 on 2021-04-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0015_auto_20210415_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='duedate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='subject',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='solution',
            name='submission_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
